/* =========================================================================
   data.jsx — dados de projetos e skills (compartilhado)
   ========================================================================= */

window.PROJECTS = [
  {
    id: "atlas-erp",
    num: "01",
    name: "Atlas ERP",
    tagline: "Núcleo de gestão empresarial modular para PMEs em crescimento.",
    glyph: "⬡",
    bg: "linear-gradient(135deg,#C2521C,#E0732E)",
    year: "2024",
    role: "Backend Lead",
    type: "Sistema ERP",
    stack: ["Java", "Spring Boot", "PostgreSQL", "Docker", "React"],
    desc: "Atlas centraliza estoque, financeiro, vendas e RH em um único painel. Arquitetura modular onde cada domínio é um serviço independente, comunicando-se por eventos. Pensado para empresas que cresceram além das planilhas mas não querem a complexidade de soluções enterprise infladas.",
    features: [
      "Controle de estoque em tempo real com alertas automáticos de reposição",
      "Módulo financeiro com fluxo de caixa projetado e DRE automatizado",
      "Permissões granulares por cargo e auditoria completa de ações",
      "API REST documentada para integrações com e-commerce e contabilidade",
    ],
    metrics: [["−40%", "tempo em tarefas manuais"], ["12", "módulos integrados"], ["99.9%", "uptime"]],
  },
  {
    id: "verdo-shop",
    num: "02",
    name: "Verdo Shop",
    tagline: "Plataforma de e-commerce headless com checkout em um clique.",
    glyph: "◗",
    bg: "linear-gradient(135deg,#1F6B4F,#2E9C73)",
    year: "2024",
    role: "FullStack",
    type: "E-commerce",
    stack: ["TypeScript", "React", "Spring Boot", "Stripe", "Redis"],
    desc: "Verdo é uma loja virtual headless onde o catálogo é desacoplado da vitrine. O backend serve produtos via API, e o frontend renderiza experiências de compra ultrarrápidas. Carrinho persistente, recomendações e um checkout que reduz o abandono ao mínimo.",
    features: [
      "Catálogo headless servido por API com cache em Redis",
      "Checkout em etapa única integrado a múltiplos gateways de pagamento",
      "Carrinho persistente entre dispositivos e sessões",
      "Painel administrativo com gestão de pedidos, cupons e relatórios",
    ],
    metrics: [["1.2s", "carregamento médio"], ["+28%", "conversão"], ["10k+", "SKUs"]],
  },
  {
    id: "lumen-finance",
    num: "03",
    name: "Lumen Finance",
    tagline: "Dashboard financeiro que transforma números em decisões.",
    glyph: "◓",
    bg: "linear-gradient(135deg,#2B4C8C,#3E6BC4)",
    year: "2023",
    role: "FullStack",
    type: "Dashboard",
    stack: ["React", "TypeScript", "Java", "Spring Boot", "Chart.js"],
    desc: "Lumen reúne contas, investimentos e despesas em uma visão única e clara. Gráficos interativos revelam padrões de gasto, projeções de saldo e metas de economia. A regra: cada dado mostrado precisa ajudar a tomar uma decisão — sem ruído.",
    features: [
      "Categorização automática de transações por machine learning de regras",
      "Projeção de saldo futuro baseada em recorrências detectadas",
      "Metas de economia com acompanhamento visual de progresso",
      "Exportação de relatórios em PDF e integração Open Finance",
    ],
    metrics: [["6", "fontes integradas"], ["realtime", "sincronização"], ["AES-256", "criptografia"]],
  },
  {
    id: "nimbus-saas",
    num: "04",
    name: "Nimbus SaaS",
    tagline: "Boilerplate multi-tenant para lançar SaaS em dias, não meses.",
    glyph: "❖",
    bg: "linear-gradient(135deg,#6B3FA0,#8B5CC4)",
    year: "2023",
    role: "Arquiteto",
    type: "Plataforma SaaS",
    stack: ["Spring Boot", "Java", "React", "PostgreSQL", "JWT"],
    desc: "Nimbus é a fundação de qualquer produto SaaS: autenticação, billing por assinatura, isolamento multi-tenant e onboarding já resolvidos. Em vez de reescrever o mesmo encanamento toda vez, você pluga sua lógica de negócio e lança.",
    features: [
      "Isolamento multi-tenant por schema com provisionamento automático",
      "Autenticação JWT + OAuth2 e fluxo completo de recuperação de conta",
      "Billing recorrente com planos, trials e upgrades sem fricção",
      "Onboarding guiado e feature flags por plano de assinatura",
    ],
    metrics: [["3 dias", "para MVP"], ["multi-tenant", "nativo"], ["∞", "tenants"]],
  },
  {
    id: "flux-automation",
    num: "05",
    name: "Flux Automation",
    tagline: "Motor de automação que conecta tudo e dorme por você.",
    glyph: "⟁",
    bg: "linear-gradient(135deg,#B0892C,#D4AB3E)",
    year: "2023",
    role: "Backend",
    type: "Automação",
    stack: ["Java", "Spring Boot", "RabbitMQ", "Docker", "Cron"],
    desc: "Flux é um orquestrador visual de fluxos de trabalho. Conecte gatilhos a ações — quando um pedido chega, dispare um e-mail, atualize a planilha, notifique o time. Filas robustas garantem que nada se perde, mesmo quando um serviço externo cai.",
    features: [
      "Editor visual de fluxos com gatilhos, condições e ações encadeadas",
      "Filas com RabbitMQ e retry exponencial para resiliência",
      "Conectores prontos para e-mail, webhooks, planilhas e APIs",
      "Agendamento por cron e execução paralela de jobs",
    ],
    metrics: [["0", "tarefas perdidas"], ["50+", "conectores"], ["24/7", "execução"]],
  },
];

window.SKILLS = [
  {
    cat: "Backend",
    icon: "server",
    items: [
      { name: "Java", lvl: 5 },
      { name: "Spring Boot", lvl: 5 },
      { name: "REST APIs", lvl: 5 },
      { name: "Microservices", lvl: 4 },
      { name: "JPA / Hibernate", lvl: 4 },
      { name: "RabbitMQ", lvl: 3 },
    ],
  },
  {
    cat: "Frontend",
    icon: "layout-dashboard",
    items: [
      { name: "React", lvl: 4 },
      { name: "TypeScript", lvl: 4 },
      { name: "JavaScript", lvl: 4 },
      { name: "HTML / CSS", lvl: 4 },
      { name: "Tailwind CSS", lvl: 4 },
    ],
  },
  {
    cat: "Dados & Infra",
    icon: "database",
    items: [
      { name: "PostgreSQL", lvl: 4 },
      { name: "MySQL", lvl: 4 },
      { name: "Docker", lvl: 4 },
      { name: "Redis", lvl: 3 },
      { name: "Linux", lvl: 3 },
    ],
  },
  {
    cat: "Ferramentas",
    icon: "wrench",
    items: [
      { name: "Git / GitHub", lvl: 5 },
      { name: "Maven", lvl: 4 },
      { name: "Insomnia", lvl: 4 },
      { name: "JUnit", lvl: 4 },
      { name: "CI/CD", lvl: 3 },
    ],
  },
];

window.TECH_GROUPS = [
  { title: "IDEs & Editores", items: ["DataGrip", "IntelliJ IDEA", "VS Code"] },
  { title: "Linguagens", items: ["Java", "JavaScript", "TypeScript", "HTML5", "CSS3"] },
  { title: "Frameworks & Bibliotecas", items: ["Spring Boot", "React", "Tailwind CSS"] },
  { title: "Bancos de Dados", items: ["PostgreSQL", "MySQL", "Redis"] },
  { title: "Sistemas Operacionais", items: ["Linux", "Windows"] },
  { title: "DevOps & Ferramentas", items: ["Docker", "Git", "RabbitMQ", "Maven", "Insomnia"] },
];
